/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all registered agents with status and labels. */
        get: operations["list_agents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Fetch a single agent. */
        get: operations["get_agent"];
        put?: never;
        post?: never;
        /** Remove an agent and its labels. */
        delete: operations["delete_agent"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agents/{id}/labels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Replace an agent's labels. */
        put: operations["put_labels"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List grouping dimensions (label keys, values, and agent counts). */
        get: operations["list_categories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent events, newest first. */
        get: operations["list_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe — the process is up and serving. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe — the process can serve real traffic. */
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description A registered agent with its derived liveness status and labels. */
        Agent: {
            /** Format: uuid */
            agent_id: string;
            /** Format: date-time */
            first_seen: string;
            host: string;
            /** @description User-defined key/value labels. */
            labels: {
                [key: string]: string;
            };
            /** Format: date-time */
            last_seen: string;
            /** @description `online` | `stale` | `offline`, derived from `last_seen`. */
            status: string;
        };
        /** @description One grouping dimension (label key) and its values. */
        CategoryDimension: {
            key: string;
            values: components["schemas"]["CategoryValue"][];
        };
        CategoryValue: {
            /** Format: int64 */
            agent_count: number;
            value: string;
        };
        /** @description Liveness response. */
        Health: {
            /** @description Always `"ok"` when the service is live. */
            status: string;
            /** @description Build version of the control plane. */
            version: string;
        };
        /** @description Readiness response. */
        Readiness: {
            /**
             * @description Per-dependency readiness (e.g. database, NATS), populated as those
             *     dependencies are wired in (#24).
             */
            checks: {
                [key: string]: boolean;
            };
            /** @description Whether the service is ready to accept traffic. */
            ready: boolean;
        };
        /**
         * @description A persisted event as returned by the read API.
         *
         *     Normalized columns are surfaced directly; `payload` and `explanation` are
         *     the raw JSON forms of the `ravn-core` types.
         */
        StoredEvent: {
            /** Format: uuid */
            agent_id: string;
            category_hints: string[];
            /** @description LLM explanation (`ravn_core::Explanation`) as JSON, if present. */
            explanation: Record<string, never>;
            host: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            observed_at: string;
            /** Format: date-time */
            occurred_at: string;
            /** @description Source-specific payload (`ravn_core::Payload`) as JSON. */
            payload: Record<string, never>;
            /**
             * Format: date-time
             * @description When the control plane ingested it.
             */
            received_at: string;
            severity: string;
            source: string;
            title: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_agents: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered agents */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"][];
                };
            };
        };
    };
    get_agent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Agent id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            /** @description Unknown agent */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_agent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Agent id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unknown agent */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    put_labels: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Agent id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            /** @description Unknown agent */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_categories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Grouping dimensions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryDimension"][];
                };
            };
        };
    };
    list_events: {
        parameters: {
            query?: {
                /** @description Maximum number of events to return (1–500, default 50). */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredEvent"][];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is live */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
}
