/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List recent events, newest first. */
        get: operations["list_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness probe — the process is up and serving. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness probe — the process can serve real traffic. */
        get: operations["ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Liveness response. */
        Health: {
            /** @description Always `"ok"` when the service is live. */
            status: string;
            /** @description Build version of the control plane. */
            version: string;
        };
        /** @description Readiness response. */
        Readiness: {
            /**
             * @description Per-dependency readiness (e.g. database, NATS), populated as those
             *     dependencies are wired in (#24).
             */
            checks: {
                [key: string]: boolean;
            };
            /** @description Whether the service is ready to accept traffic. */
            ready: boolean;
        };
        /**
         * @description A persisted event as returned by the read API.
         *
         *     Normalized columns are surfaced directly; `payload` and `explanation` are
         *     the raw JSON forms of the `ravn-core` types.
         */
        StoredEvent: {
            /** Format: uuid */
            agent_id: string;
            category_hints: string[];
            /** @description LLM explanation (`ravn_core::Explanation`) as JSON, if present. */
            explanation: Record<string, never>;
            host: string;
            /** Format: uuid */
            id: string;
            /** Format: date-time */
            observed_at: string;
            /** Format: date-time */
            occurred_at: string;
            /** @description Source-specific payload (`ravn_core::Payload`) as JSON. */
            payload: Record<string, never>;
            /**
             * Format: date-time
             * @description When the control plane ingested it.
             */
            received_at: string;
            severity: string;
            source: string;
            title: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_events: {
        parameters: {
            query?: {
                /** @description Maximum number of events to return (1–500, default 50). */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent events */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoredEvent"][];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is live */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Service is ready */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Readiness"];
                };
            };
        };
    };
}
