//! Prometheus metrics for the control plane (#40).
//!
//! Exposes ingestion rate, heartbeats, errors, and agent liveness at
//! `/metrics` so Ravn can scrape its own control plane. (OpenTelemetry traces
//! and agent-side metrics are a follow-on.)

use prometheus::{Encoder, IntCounter, IntCounterVec, IntGaugeVec, Opts, Registry, TextEncoder};

pub struct Metrics {
    registry: Registry,
    /// Events ingested, labeled by severity.
    pub events_ingested: IntCounterVec,
    /// Heartbeats received.
    pub heartbeats: IntCounter,
    /// Ingestion failures (persist errors, malformed payloads).
    pub ingest_errors: IntCounter,
    /// K8s-event explanations generated by the shared inference endpoint (#58).
    pub explanations_generated: IntCounter,
    /// K8s-event explanation attempts that failed (endpoint slow/unreachable).
    pub explanation_errors: IntCounter,
    /// Registered agents by liveness status (set at scrape time).
    agents: IntGaugeVec,
}

impl Metrics {
    pub fn new() -> Self {
        let registry = Registry::new();
        let events_ingested = IntCounterVec::new(
            Opts::new("ravn_events_ingested_total", "Events ingested by the control plane"),
            &["severity"],
        )
        .expect("valid metric");
        let heartbeats =
            IntCounter::new("ravn_heartbeats_total", "Agent heartbeats received").expect("valid metric");
        let ingest_errors =
            IntCounter::new("ravn_ingest_errors_total", "Ingestion failures").expect("valid metric");
        let explanations_generated = IntCounter::new(
            "ravn_explanations_generated_total",
            "K8s-event explanations generated by the inference endpoint",
        )
        .expect("valid metric");
        let explanation_errors = IntCounter::new(
            "ravn_explanation_errors_total",
            "K8s-event explanation attempts that failed",
        )
        .expect("valid metric");
        let agents = IntGaugeVec::new(
            Opts::new("ravn_agents", "Registered agents by liveness status"),
            &["status"],
        )
        .expect("valid metric");

        registry.register(Box::new(events_ingested.clone())).unwrap();
        registry.register(Box::new(heartbeats.clone())).unwrap();
        registry.register(Box::new(ingest_errors.clone())).unwrap();
        registry.register(Box::new(explanations_generated.clone())).unwrap();
        registry.register(Box::new(explanation_errors.clone())).unwrap();
        registry.register(Box::new(agents.clone())).unwrap();

        Self {
            registry,
            events_ingested,
            heartbeats,
            ingest_errors,
            explanations_generated,
            explanation_errors,
            agents,
        }
    }

    /// Set the agent liveness gauges (called before each scrape).
    pub fn set_agent_counts(&self, online: i64, stale: i64, offline: i64) {
        self.agents.with_label_values(&["online"]).set(online);
        self.agents.with_label_values(&["stale"]).set(stale);
        self.agents.with_label_values(&["offline"]).set(offline);
    }

    /// Render the metrics in Prometheus text exposition format.
    pub fn encode(&self) -> String {
        let mut buf = Vec::new();
        let encoder = TextEncoder::new();
        let _ = encoder.encode(&self.registry.gather(), &mut buf);
        String::from_utf8(buf).unwrap_or_default()
    }
}

impl Default for Metrics {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn counters_render_in_exposition_format() {
        let m = Metrics::new();
        m.events_ingested.with_label_values(&["warning"]).inc();
        m.heartbeats.inc();
        m.set_agent_counts(2, 1, 0);
        let out = m.encode();
        assert!(out.contains("ravn_events_ingested_total"));
        assert!(out.contains("severity=\"warning\""));
        assert!(out.contains("ravn_heartbeats_total"));
        assert!(out.contains("ravn_agents"));
        assert!(out.contains("status=\"online\""));
    }
}
