//! Prometheus metrics for the control plane (#40, #149).
//!
//! Exposes ingestion rate, heartbeats, errors, and agent liveness at
//! `/metrics` so Ravn can scrape its own control plane. Extended in #149
//! to cover self-observability: remediation outcomes, circuit-breaker trips,
//! inference latency/failures, and kill-switch state.
//!
//! Metric inventory:
//! - `ravn_events_ingested_total{severity}` — events through the ingest path
//! - `ravn_heartbeats_total` — heartbeat pulses received
//! - `ravn_ingest_errors_total` — persist / decode failures on ingest
//! - `ravn_explanations_generated_total` — K8s-event explanations produced
//! - `ravn_explanation_errors_total` — explanation attempts that failed
//! - `ravn_agents{status}` — gauge: online / stale / offline agent counts
//! - `ravn_remediation_outcomes_total{status}` — per-ActionStatus counter
//! - `ravn_remediation_proposed_total{decision}` — auto / approve / forbid
//! - `ravn_circuit_breaker_trips_total` — times the breaker downgraded auto → approve
//! - `ravn_kill_switch_active` — 1 when auto-remediation is globally disabled
//! - `ravn_inference_latency_seconds` — histogram of successful inference calls
//! - `ravn_inference_timeouts_total` — inference calls that exceeded the deadline
//! - `ravn_command_channel_errors_total` — failures enqueuing / delivering commands

use prometheus::{
    Encoder, Histogram, HistogramOpts, IntCounter, IntCounterVec, IntGauge, IntGaugeVec, Opts,
    Registry, TextEncoder,
};

pub struct Metrics {
    registry: Registry,
    /// Events ingested, labeled by severity.
    pub events_ingested: IntCounterVec,
    /// Heartbeats received.
    pub heartbeats: IntCounter,
    /// Ingestion failures (persist errors, malformed payloads).
    pub ingest_errors: IntCounter,
    /// K8s-event explanations generated by the shared inference endpoint (#58).
    pub explanations_generated: IntCounter,
    /// K8s-event explanation attempts that failed (endpoint slow/unreachable).
    pub explanation_errors: IntCounter,
    /// Registered agents by liveness status (set at scrape time).
    agents: IntGaugeVec,

    // ── #149 new metrics ──────────────────────────────────────────────────────

    /// Remediation actions closed with a final ActionStatus from the agent.
    pub remediation_outcomes: IntCounterVec,
    /// Remediation proposals created, labeled by the policy decision taken
    /// (`auto`, `approve`, `forbid`).
    pub remediation_proposed: IntCounterVec,
    /// Circuit-breaker trips: each time an `auto` decision was downgraded to
    /// `approve` because the (host, template) hit rate limit.
    pub circuit_breaker_trips: IntCounter,
    /// 1 when the global auto-remediation kill switch is active, 0 otherwise.
    pub kill_switch_active: IntGauge,
    /// Latency histogram for successful inference calls (seconds).
    pub inference_latency_seconds: Histogram,
    /// Inference calls that exceeded the configured deadline.
    pub inference_timeouts: IntCounter,
    /// Failures on the command channel (build / enqueue / delivery errors).
    pub command_channel_errors: IntCounter,
}

impl Metrics {
    pub fn new() -> Self {
        let registry = Registry::new();

        // ── existing ──────────────────────────────────────────────────────────
        let events_ingested = IntCounterVec::new(
            Opts::new("ravn_events_ingested_total", "Events ingested by the control plane"),
            &["severity"],
        )
        .expect("valid metric");
        let heartbeats =
            IntCounter::new("ravn_heartbeats_total", "Agent heartbeats received").expect("valid metric");
        let ingest_errors =
            IntCounter::new("ravn_ingest_errors_total", "Ingestion failures").expect("valid metric");
        let explanations_generated = IntCounter::new(
            "ravn_explanations_generated_total",
            "K8s-event explanations generated by the inference endpoint",
        )
        .expect("valid metric");
        let explanation_errors = IntCounter::new(
            "ravn_explanation_errors_total",
            "K8s-event explanation attempts that failed",
        )
        .expect("valid metric");
        let agents = IntGaugeVec::new(
            Opts::new("ravn_agents", "Registered agents by liveness status"),
            &["status"],
        )
        .expect("valid metric");

        // ── #149 ──────────────────────────────────────────────────────────────
        let remediation_outcomes = IntCounterVec::new(
            Opts::new(
                "ravn_remediation_outcomes_total",
                "Remediation actions closed, labeled by the agent-reported ActionStatus",
            ),
            &["status"],
        )
        .expect("valid metric");
        let remediation_proposed = IntCounterVec::new(
            Opts::new(
                "ravn_remediation_proposed_total",
                "Remediation proposals created, by policy decision (auto|approve|forbid)",
            ),
            &["decision"],
        )
        .expect("valid metric");
        let circuit_breaker_trips = IntCounter::new(
            "ravn_circuit_breaker_trips_total",
            "Times the policy circuit breaker downgraded auto → approve",
        )
        .expect("valid metric");
        let kill_switch_active = IntGauge::new(
            "ravn_kill_switch_active",
            "1 when the global auto-remediation kill switch is on (RAVN_REMEDIATION_AUTO=0)",
        )
        .expect("valid metric");
        let inference_latency_seconds = Histogram::with_opts(
            HistogramOpts::new(
                "ravn_inference_latency_seconds",
                "Latency of successful inference calls in seconds",
            )
            .buckets(vec![0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 20.0, 30.0]),
        )
        .expect("valid metric");
        let inference_timeouts = IntCounter::new(
            "ravn_inference_timeouts_total",
            "Inference calls that exceeded the configured deadline",
        )
        .expect("valid metric");
        let command_channel_errors = IntCounter::new(
            "ravn_command_channel_errors_total",
            "Failures on the remediation command channel (build / enqueue / delivery)",
        )
        .expect("valid metric");

        // ── register ──────────────────────────────────────────────────────────
        for m in [
            Box::new(events_ingested.clone()) as Box<dyn prometheus::core::Collector>,
            Box::new(heartbeats.clone()),
            Box::new(ingest_errors.clone()),
            Box::new(explanations_generated.clone()),
            Box::new(explanation_errors.clone()),
            Box::new(agents.clone()),
            Box::new(remediation_outcomes.clone()),
            Box::new(remediation_proposed.clone()),
            Box::new(circuit_breaker_trips.clone()),
            Box::new(kill_switch_active.clone()),
            Box::new(inference_latency_seconds.clone()),
            Box::new(inference_timeouts.clone()),
            Box::new(command_channel_errors.clone()),
        ] {
            registry.register(m).expect("metric registered once");
        }

        Self {
            registry,
            events_ingested,
            heartbeats,
            ingest_errors,
            explanations_generated,
            explanation_errors,
            agents,
            remediation_outcomes,
            remediation_proposed,
            circuit_breaker_trips,
            kill_switch_active,
            inference_latency_seconds,
            inference_timeouts,
            command_channel_errors,
        }
    }

    /// Set the agent liveness gauges (called before each scrape).
    pub fn set_agent_counts(&self, online: i64, stale: i64, offline: i64) {
        self.agents.with_label_values(&["online"]).set(online);
        self.agents.with_label_values(&["stale"]).set(stale);
        self.agents.with_label_values(&["offline"]).set(offline);
    }

    /// Record a closed remediation outcome by its ActionStatus string.
    pub fn record_remediation_outcome(&self, status: &str) {
        self.remediation_outcomes.with_label_values(&[status]).inc();
    }

    /// Record a policy decision taken at Prepare time.
    pub fn record_remediation_proposed(&self, decision: &str) {
        self.remediation_proposed.with_label_values(&[decision]).inc();
    }

    /// Render the metrics in Prometheus text exposition format.
    pub fn encode(&self) -> String {
        let mut buf = Vec::new();
        let encoder = TextEncoder::new();
        let _ = encoder.encode(&self.registry.gather(), &mut buf);
        String::from_utf8(buf).unwrap_or_default()
    }
}

impl Default for Metrics {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn counters_render_in_exposition_format() {
        let m = Metrics::new();
        m.events_ingested.with_label_values(&["warning"]).inc();
        m.heartbeats.inc();
        m.set_agent_counts(2, 1, 0);
        let out = m.encode();
        assert!(out.contains("ravn_events_ingested_total"));
        assert!(out.contains("severity=\"warning\""));
        assert!(out.contains("ravn_heartbeats_total"));
        assert!(out.contains("ravn_agents"));
        assert!(out.contains("status=\"online\""));
    }

    #[test]
    fn issue_149_metrics_render() {
        let m = Metrics::new();
        m.remediation_outcomes.with_label_values(&["succeeded"]).inc();
        m.remediation_proposed.with_label_values(&["auto"]).inc();
        m.circuit_breaker_trips.inc();
        m.kill_switch_active.set(1);
        m.inference_latency_seconds.observe(1.2);
        m.inference_timeouts.inc();
        m.command_channel_errors.inc();
        let out = m.encode();
        assert!(out.contains("ravn_remediation_outcomes_total"));
        assert!(out.contains("status=\"succeeded\""));
        assert!(out.contains("ravn_remediation_proposed_total"));
        assert!(out.contains("decision=\"auto\""));
        assert!(out.contains("ravn_circuit_breaker_trips_total"));
        assert!(out.contains("ravn_kill_switch_active"));
        assert!(out.contains("ravn_inference_latency_seconds"));
        assert!(out.contains("ravn_inference_timeouts_total"));
        assert!(out.contains("ravn_command_channel_errors_total"));
    }
}
