//! Enrollment wire types (#19): the bootstrap-token → mTLS-credential exchange.
//!
//! An agent proves it holds a shared bootstrap token, sends a certificate
//! signing request, and receives a per-agent client certificate signed by the
//! control plane's internal CA (the agent-credential mechanism of #26). The
//! exchange is idempotent: re-enrolling the same `agent_id` simply re-issues.

use chrono::{DateTime, Utc};
use schemars::JsonSchema;
use serde::{Deserialize, Serialize};

use crate::event::AgentId;

/// Sent by the agent to `POST /enroll`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct EnrollRequest {
    /// Shared bootstrap token authorising enrollment. Never logged.
    pub bootstrap_token: String,
    /// The agent's stable identity (assigned locally, bound into the cert).
    pub agent_id: AgentId,
    /// Hostname, recorded in the registry.
    pub host: String,
    /// PEM-encoded PKCS#10 certificate signing request generated by the agent.
    pub csr_pem: String,
}

/// Returned on a successful enrollment.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize, JsonSchema)]
pub struct EnrollResponse {
    /// Echoes the enrolled agent's identity.
    pub agent_id: AgentId,
    /// PEM client certificate signed by the control-plane CA. Its identity is
    /// bound to `agent_id` regardless of what the CSR's subject claimed.
    pub certificate_pem: String,
    /// PEM CA certificate the agent should trust/pin for the transport.
    pub ca_certificate_pem: String,
    /// Base64 Ed25519 public key the control plane signs remediation commands
    /// with (#114). The agent pins this and rejects any command whose signature
    /// does not verify against it.
    pub command_signing_pubkey: String,
    /// When the issued certificate expires.
    pub not_after: DateTime<Utc>,
}
